FROM ubuntu:latest
RUN apt-get update && apt-get install python3-pip -y cron && pip3 install requests simplejson regex pymongo
ADD dst_airlines_functions.py /home/dstairline_project/dst_airlines_functions.py
ADD mongo_atlas_connection.py /home/dstairline_project/mongo_atlas_connection.py
ADD routes_cron.py /home/dstairline_project/routes_cron.py
ADD crontab /etc/cron.d/crontab
WORKDIR /home/dstairline_project/
RUN chmod 774 /tmp/crontab.urUjBA/crontab && crontab /tmp/crontab.urUjBA/crontab
ENTRYPOINT ["cron", "-f"]